[project]
name = "sec_sentiment_rag"
version = "0.0.1"
authors = [{ name = "miguel-prto" }]
requires-python = ">=3.12,<3.13"
dependencies = [
    "python-dotenv>=1.0",
    "beautifulsoup4>=4.12",
    "regex>=2024.11.6",
    "databricks-ai-search>=0.78",
    "databricks-sdk>=0.144.0",
    "pandas>=2.3",
    "requests>=2.34.2",
    "sentence-transformers>=6.1.0",
    "streamlit>=1.64.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "ipykernel",
]

databricks = [
    "databricks-connect==16.1.7",
]

[tool.ruff]
line-length = 120

[tool.uv]
package = false
